### ISSUE TITLE
add all of my followers

### ISSUE THREAD

**Issue by purzelrakete** [michenriksen/birdwatcher#1]
a module to add all of my followers would be convenient.

**Comment by michenriksen** [comment]
I did some research into this and found out that the endpoint for retrieving followers is [heavily rate-limited](https://dev.twitter.com/rest/public/rate-limits) (I guess to protect their social graph from being harvested) so a module like this would take quite a while to finish if the user has a lot of followers. 

Another problem is that the Twitter gem I use to communicate with the API does not handle rate limiting very elegantly and would actually hit the rate limits which Twitter will punish by invalidating the keys if it happens too much.

If the Twitter gem gets better at handling rate limits, I will look into a module like this.
