### ISSUE TITLE
birdwatcher database failed 

### ISSUE THREAD

**Issue by alianefromsun** [michenriksen/birdwatcher#14]
I hope this message finds you well !!
after installing birdwatcher as described here **https://github.com/michenriksen/birdwatcher**
I got an error in the section where it says 
**[+] preparing database... failed.
[-]           PG; ;connectionBad: could not translate host name "birdwatcher" to address: name or service not known**

I hope that you my way out of that issue.

sincerely

**Comment by michenriksen** [comment]
Hi there, it looks like you have given Birdwatcher incorrect database details. It is currently trying to use `birdwatcher` as the hostname of the database, which it is complaining about because it can't resolve that hostname.
