### ISSUE TITLE
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

### ISSUE THREAD

**Issue by bl4ckh0l3z** [michenriksen/birdwatcher#2]
xyz@xyz:~/Downloads/birdwatcher$ birdwatcher 
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
/usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in require: cannot load such file -- readline (LoadError)
from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in require
from /usr/local/lib/ruby/gems/2.2.0/gems/birdwatcher-0.1.0/exe/birdwatcher:4:in <top (required)>
from /usr/local/bin/birdwatcher:22:in load
from /usr/local/bin/birdwatcher:22:in <main>
# 

Linux xyz 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
gem 2.6.7
All dependecies are installed...

Thanks,
Cheers

**Comment by michenriksen** [comment]
The RMagick deprecation warning is just a warning and is triggered by a gem including rmagick. The error you get is because it seems like Ruby has not been compiled with `readline` support.

Maybe doing `sudo apt-get install libreadline-dev` and installing Ruby with [RVM](https://rvm.io/) will fix it?

**Comment by TamanShud** [comment]
Have similar issue and have libreadline-dev and Ruby with RVM. 

[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require': libMagickCore-6.Q16.so.2: cannot open shared object file: No such file or directory - /var/lib/gems/2.3.0/gems/rmagick-2.16.0/lib/RMagick2.so (LoadError)
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/rmagick-2.16.0/lib/rmagick_internal.rb:12:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/rmagick-2.16.0/deprecated/RMagick.rb:6:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/magic_cloud-0.0.4/lib/magic_cloud/canvas.rb:2:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/magic_cloud-0.0.4/lib/magic_cloud/cloud.rb:3:in `require_relative'
	from /var/lib/gems/2.3.0/gems/magic_cloud-0.0.4/lib/magic_cloud/cloud.rb:3:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/magic_cloud-0.0.4/lib/magic_cloud.rb:7:in `require_relative'
	from /var/lib/gems/2.3.0/gems/magic_cloud-0.0.4/lib/magic_cloud.rb:7:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /var/lib/gems/2.3.0/gems/birdwatcher-0.4.0/lib/birdwatcher.rb:14:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/birdwatcher-0.4.0/exe/birdwatcher:3:in `<top (required)>'
	from /usr/local/bin/birdwatcher:22:in `load'
	from /usr/local/bin/birdwatcher:22:in `<main>'
