### ISSUE TITLE
Feature Request:  Add scheduled download

### ISSUE THREAD

**Issue by DigiAngel** [michenriksen/birdwatcher#3]
This app looks pretty cool....my plan is to let it run almost like a background service...is there a way to have this download tweets at a set interval?  Thank you.

**Comment by michenriksen** [comment]
Hey there,

Currently there is no built-in way to execute commands on a schedule but it's an interesting idea though!

As a "hack" you could use a resource file with the following content:

```
workspace <your workspace name>
statuses fetch
exit
```

Save that file somewhere, e.g. `~/status_fetch.res`. You can use this resource file to trigger a scheduled update with Cron, for example:

```
0 * * * * echo "resource ~/fetch_status.res" | birdwatcher >/dev/null 2>&1
```

This will kick off the command `resource ~/fetch_status.res` in Birdwatcher every hour.

Hope that helps you!

**Comment by DigiAngel** [comment]
That'll work thanks!  I'll test, share my results, and then close this ticket unless you think it might be a viable FR.  Thanks for the great app!

**Comment by DigiAngel** [comment]
Cron worked...thanks again!
